##
# configuration for i2br
#
destination: ./_site
auto:        false
lsi:         false
server_port: 4002
pygments:    false
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
exclude:
  - config.rb
  - rakefile
  - nbproject